[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pulp-docs"
version = "0.0.1"
dependencies = [
    "mkdocs-material",
    "mkdocstrings",
    "mkdocstrings-python>=1.9.1",
    "mkdocs-macros-plugin",
    "mkdocs-site-urls",
    "dynaconf",
    "importlib_resources",
    "httpx",
    "rich",
]

[project.scripts]
pulp-docs = "pulp_docs.cli:main"

[tool.setuptools]
include-package-data=true

[tool.setuptools.package-data]
pulp_docs = ["data/**"]

[tool.setuptools.packages.find]
where = ["src"]

